export const mockEventData = [
  {
    id: 1,
    creator: 2,
    title: "Концерт группы 'Ария'",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Крокус Сити Холл, Москва",
    price: "3000",
    authorName: "Иван Петров",
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    prime: true,
    image:
      "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F988346613%2F17568602339%2F1%2Foriginal.20250320-093349?w=512&auto=format%2Ccompress&q=75&sharp=10&rect=14%2C0%2C1186%2C593&s=7d8fe4225d9ca181109e6120d4c21b16",
  },
  {
    id: 2,
    creator: 2,
    title: "Курс бариста для людей с нейроотличиями, 16+, круто будет приходите все",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Online",
    price: null,
    authorName: "Иван Петров",
    prime: true,
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    image:
      "https://ucare.timepad.ru/ca459045-0e41-407c-a117-5b64a1b22470/-/format/jpeg/-/quality/smart/-/preview/1360x765/",
  },
  {
    id: 3,
    creator: 3,
    title: "Концерт группы 'Ария'",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Крокус Сити Холл, Москва",
    price: "null",
    authorName: "Иван Петров",
    prime: false,
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    image:
      "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
  },
  {
    id: 4,
    creator: 3,
    title: "Концерт группы 'Ария'",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Крокус Сити Холл, Москва",
    price: "3000",
    authorName: "Иван Петров",
    prime: false,
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    image:
      "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
  },
  {
    id: 5,
    creator: 1,
    title: "Концерт группы 'Ария'",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Online",
    price: "3000",
    authorName: "Иван Петров",
    prime: false,
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    image:
      "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
  },
  {
    id: 6,
    creator: 5,
    title: "Концерт группы 'Ария'",
    description: "Легендарная группа исполняет свои лучшие хиты",
    time: "25 мая • 20:00",
    location: "Крокус Сити Холл, Москва",
    price: "3000",
    authorName: "Иван Петров",
    prime: true,
    authorAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    image:
      "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
  },
];
